name: Demo Date Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  print_datetime:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Print Current Date and Time
        run: |
          echo "Current Date and Time: $(date)"


