name: Print Date and Time

on: [push]  # Jab bhi koi push kare, yeh workflow chalega

jobs:
  print_datetime:
    runs-on: ubuntu-latest
    steps:
      - name: Print Current Date and Time
        run: echo "Current Date and Time: $(date)"
